# Generated by Django 5.2.9 on 2025-12-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='end_shift',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='start_shift',
            field=models.TimeField(null=True),
        ),
    ]
