# Generated by Django 5.2.9 on 2025-12-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0002_doctor_end_shift_doctor_start_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='end_shift',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='start_shift',
        ),
        migrations.CreateModel(
            name='DoctorShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='surgery.doctor')),
            ],
        ),
    ]
