# Generated by Django 5.2.9 on 2025-12-18 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0003_remove_doctor_end_shift_remove_doctor_start_shift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='surgery',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='surgery.room'),
        ),
        migrations.AlterUniqueTogether(
            name='surgery',
            unique_together={('room', 'date')},
        ),
        migrations.CreateModel(
            name='RoomDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='surgery.room')),
            ],
        ),
    ]
