# Generated by Django 5.2.9 on 2025-12-22 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery', '0004_room_surgery_date_surgery_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='scans',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='status',
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='PatientScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='patients/scans/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='surgery.patient')),
            ],
        ),
    ]
